from django.urls import path
from adminApp import views


urlpatterns = [
   
   path('', views.index, name='index'),
   path('adminlogin', views.adminLogin, name='adminlogin'),
   path('addMedicalOfficer', views.addMedicalOfficer, name='addMedicalOfficer'),
   path('submitMedicalOfficer', views.submitMedicalOfficer, name='submitMedicalOfficer'),
   path('ViewMedicalOfficer', views.ViewMedicalOfficer, name='ViewMedicalOfficer'),
   path('deleteMedOfficer/<int:cr_id>/', views.deleteMedOfficer, name="deleteMedOfficer"),
   path('ViewLegalOfficer', views.ViewLegalOfficer, name='ViewLegalOfficer'),
   path('deleteLegalOfficer/<int:cr_id>/', views.deleteLegalOfficer, name="deleteLegalOfficer"),
   path('submitLegalOfficerReject/<int:cr_id>/', views.submitLegalOfficerReject, name="submitLegalOfficerReject"),
   path('submitLegalOfficerAccept/<int:cr_id>/', views.submitLegalOfficerAccept, name="submitLegalOfficerAccept"),
   path('submitMedicalOfficerReject/<int:cr_id>/', views.submitMedicalOfficerReject, name="submitMedicalOfficerReject"),
   path('submitMedicalOfficerAccept/<int:cr_id>/', views.submitMedicalOfficerAccept, name="submitMedicalOfficerAccept"),
   path('AcceptUserWithReason/<int:cr_id>/', views.AcceptUserWithReason, name="AcceptUserWithReason"),
   path('RejectUserWithReason/<int:cr_id>/', views.RejectUserWithReason, name="RejectUserWithReason"),
   path('submitEventReject/<int:cr_id>/', views.submitEventReject, name="submitEventReject"),
   path('postponeEvent/<int:cr_id>/', views.postponeEvent, name="postponeEvent"),
   path('ListMemberEvents/<int:cr_id>/', views.ListMemberEvents, name="ListMemberEvents"),
   path('ViewBoardMembers', views.ViewBoardMembers, name='ViewBoardMembers'),
   path('ViewRejectedBoardMembers', views.ViewRejectedBoardMembers, name='ViewRejectedBoardMembers'),
   path('ViewAcceptedBoardMembers', views.ViewAcceptedBoardMembers, name='ViewAcceptedBoardMembers'),
   path('viewAcceptedMedicalOfficer', views.viewAcceptedMedicalOfficer, name='viewAcceptedMedicalOfficer'),
   path('viewAcceptedLegalOfficer', views.viewAcceptedLegalOfficer, name='viewAcceptedLegalOfficer'),
   path('ViewUsers', views.ViewUsers, name='ViewUsers'),
   path('ViewRejectedUsers', views.ViewRejectedUsers, name='ViewRejectedUsers'),
   path('ViewAcceptedUsers', views.ViewAcceptedUsers, name='ViewAcceptedUsers'),
   path('acceptBoardMember/<int:cr_id>/', views.acceptBoardMember, name="acceptBoardMember"),
   path('AcceptBoardmemberWithReason/<int:cr_id>/', views.AcceptBoardmemberWithReason, name="AcceptBoardmemberWithReason"),
   path('RejectBoardmemberWithReason/<int:cr_id>/', views.RejectBoardmemberWithReason, name="RejectBoardmemberWithReason"),
   path('RejectBoardMember/<int:cr_id>/', views.RejectBoardMember, name="RejectBoardMember"),
   path('acceptUser/<int:cr_id>/', views.acceptUser, name="acceptUser"),
   path('RejectUser/<int:cr_id>/', views.RejectUser, name="RejectUser"),
   path('Addevent', views.Addevent, name='Addevent'),
   path('Viewevent', views.Viewevent, name='Viewevent'),
   path('ViewBoardMemberEvents', views.ViewBoardMemberEvents, name='ViewBoardMemberEvents'),
   path('submitEvent', views.submitEvent, name='submitEvent'),
   path('deleteEvent/<int:cr_id>/', views.deleteEvent, name="deleteEvent"),
   path('Addshelter', views.Addshelter, name='Addshelter'),
   path('Viewshelter', views.Viewshelter, name='Viewshelter'),
   path('submitShelter', views.submitShelter, name='submitShelter'),
   path('deleteShelter/<int:cr_id>/', views.deleteShelter, name="deleteShelter"),
   path('AddJobVacancy', views.AddJobVacancy, name='AddJobVacancy'),
   path('ViewJobVacancy', views.ViewJobVacancy, name='ViewJobVacancy'),
   path('submitJobVacancy', views.submitJobVacancy, name='submitJobVacancy'),
   path('deleteJobVacancy/<int:cr_id>/', views.deleteJobVacancy, name="deleteJobVacancy"),
   path('editEvent/<int:cr_id>/', views.editEvent, name="editEvent"),
   path('submitEditedEvent/<int:cr_id>/', views.submitEditedEvent, name="submitEditedEvent"),
   path('AddEducation', views.AddEducation, name='AddEducation'),
   path('ViewEducation', views.ViewEducation, name='ViewEducation'),
   path('submitEducation', views.submitEducation, name='submitEducation'),
   path('deleteInstitution/<int:cr_id>/', views.deleteInstitution, name="deleteInstitution"),
   path('viewMedicalBooking', views.viewMedicalBooking, name='viewMedicalBooking'),
   path('viewLegalbooking', views.viewLegalbooking, name='viewLegalbooking'),
   path('viewRejectedLegalOfficer', views.viewRejectedLegalOfficer, name='viewRejectedLegalOfficer'),
   path('viewRejectedMedicalOfficer', views.viewRejectedMedicalOfficer, name='viewRejectedMedicalOfficer'),
   path('searchUsers', views.searchUsers, name='searchUsers'),
   path('searchBoardmember', views.searchBoardmember, name='searchBoardmember'),
   path('searchMedicalOfficers', views.searchMedicalOfficers, name='searchMedicalOfficers'),
   path('searchLegalOfficers', views.searchLegalOfficers, name='searchLegalOfficers'),
   path('ViewBoardMemberEvents', views.ViewBoardMemberEvents, name='ViewBoardMemberEvents'),
   path('searchCourse', views.searchCourse, name='searchCourse'),

]